---
environment:
    matrix:
    - TOXENV: py37
      TOXPYTHON: C:\Python37\python.exe
      PYTHON_HOME: C:\Python37
      PYTHON_VERSION: '3.7'
      PYTHON_ARCH: '32'
    - TOXENV: py37
      TOXPYTHON: C:\Python37-x64\python.exe
      PYTHON_HOME: C:\Python37-x64
      PYTHON_VERSION: '3.7'
      PYTHON_ARCH: '64'
    #- TOXENV: py37-nocov
    #  TOXPYTHON: C:\Python37\python.exe
    #  PYTHON_HOME: C:\Python37
    #  PYTHON_VERSION: '3.7'
    #  PYTHON_ARCH: '32'
    #- TOXENV: py37-nocov
    #  TOXPYTHON: C:\Python37-x64\python.exe
    #  PYTHON_HOME: C:\Python37-x64
    #  PYTHON_VERSION: '3.7'
    #  PYTHON_ARCH: '64'

build: off

init:    
  - ps: echo $env:TOXENV    
  - ps: ls C:\Python*    
install:    
    - '%PYTHON_HOME%\python -mpip install --progress-bar=off tox -rdevtools/requirements.txt'
    - '%PYTHON_HOME%\Scripts\virtualenv --version'    
    - '%PYTHON_HOME%\Scripts\easy_install --version'    
    - '%PYTHON_HOME%\Scripts\pip --version'    
    - '%PYTHON_HOME%\Scripts\tox --version'  

test_script:
    - '%PYTHON_HOME%\Scripts\tox'
